pipeline:
  agent:
    any: {}
  stages:
    - stage: "Code Quality Check"
      steps:
        - sh "echo 'Running Linters...'"
        - sh "npm run lint"
    - stage: "Application Testing"
      steps:
        - sh "echo 'Running Unit Tests...'"
        - sh "npm run test"
    - stage: "Deployment"
      when:
        branch: "main"
      steps:
        - sh "echo 'Deploying application to Production...'"
